output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["1"]

data_root_dir: "/data/home/zhongyisun/data/drink/onedet_cache"

train:
    dataset: "train"
    stdout: False
    gpus: "2"
    nworkers: 8
    pin_mem: False

    momentum: 0.9
    decay: 0.001

    clear: False

    warmup_lr: 0.00005
    lr_steps: [1000, 8000, 10000]
    lr_rates: [0.001, 0.0001, 0.00001]
    max_batches: 15000
    resize_interval: 104

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [1000]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 1
    weights: "weights/darknet53.conv.74"

test:
    dataset: "test"
    stdout: True
    gpus: "2"
    nworkers: 8
    pin_mem: True

    input_shape: [960, 960]
    batch_size: 8
    weights: "outputs/Yolov3/baseline/weights/weights_13000.pt"

    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "7"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
